# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestReview():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_review(self):
    self.driver.get("http://localhost/miniproject1/index.php")
    self.driver.set_window_size(1552, 832)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".swiper-slide-next img").click()
    self.vars["win6490"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win6490"])
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(1) .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".write-review-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".star-rating > label:nth-child(4)").click()
    self.driver.find_element(By.ID, "reviewText").click()
    self.driver.find_element(By.ID, "reviewText").send_keys("Really cool outfit. Totally recommend this. Used it for my haldi and was worth it")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
