# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOutfitviewing():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_outfitviewing(self):
    self.driver.get("http://localhost/miniproject1/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.LINK_TEXT, "RENT OUTFITS").click()
    self.driver.find_element(By.ID, "signup_email").send_keys("keerthanathomas097@gmail.com")
    self.driver.find_element(By.ID, "signup_password").send_keys("passwordP#")
    self.driver.find_element(By.ID, "signin_email").send_keys("keerthanathomas097@gmail.com")
    self.driver.find_element(By.ID, "signin_password").send_keys("passwordP#")
    self.driver.find_element(By.NAME, "signin").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".swiper-slide-next img").click()
    self.vars["win4973"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win4973"])
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(2) .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".thumbnail:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".thumbnail:nth-child(3)").click()
    self.driver.find_element(By.NAME, "height").click()
    self.driver.find_element(By.NAME, "height").send_keys("67")
    self.driver.find_element(By.NAME, "shoulder").send_keys("34")
    self.driver.find_element(By.NAME, "bust").click()
    self.driver.find_element(By.NAME, "bust").send_keys("30")
    self.driver.find_element(By.NAME, "waist").click()
    self.driver.find_element(By.NAME, "waist").send_keys("45")
    self.driver.find_element(By.ID, "5days").click()
    self.driver.find_element(By.ID, "eventDate").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flatpickr-day:nth-child(25)").click()
    self.driver.find_element(By.ID, "eventDate").send_keys("2025-04-23")
  
