# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.chrome.options import Options

class TestOutfitviewing2():
    def setup_method(self):
        chrome_options = Options()
        chrome_options.add_argument('--start-maximized')
        self.driver = webdriver.Chrome(options=chrome_options)
        print("Browser opened")
  
    def test_outfitviewing2(self):
        try:
            # Just navigate through the pages
            print("Starting navigation...")
            
            # Go to index
            self.driver.get("http://localhost/miniproject1/index.php")
            time.sleep(2)
            print("On index page")
            
            # Go to outfit.php
            self.driver.get("http://localhost/miniproject1/outfit.php")
            time.sleep(2)
            print("On outfit page")
            
            # Go directly to rentnow.php with ID 11
            self.driver.get("http://localhost/miniproject1/rentnow.php?id=11")
            time.sleep(3)
            print("On rentnow page")
            
            # Take screenshot
            self.driver.save_screenshot("rentnow_screenshot.png")
            print("Screenshot saved!")
            
            time.sleep(2)  # Wait a bit before closing
            return True

        except Exception as e:
            print(f"Error: {str(e)}")
            return True

if __name__ == "__main__":
    test = TestOutfitviewing2()
    try:
        test.setup_method()
        test.test_outfitviewing2()
        print("Done!")
    finally:
        if hasattr(test, 'driver'):
            test.driver.quit()
  
